### ISSUE TITLE
AttributeError: width

### ISSUE THREAD

**Issue by Diphendara** [desdic/beads#1]
I just execute the sh for examples and not working, i install all the requirements

Traceback (most recent call last):
  File "./beads.py", line 216, in <module>
    main(image,bgcolor,xgrid,ygrid,fastcolor,beadslist,numworkers,mode,output)
  File "./beads.py", line 113, in main
    optimalx = int(origimage.width/xgrid)*xgrid
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 528, in **getattr**
    raise AttributeError(name)
AttributeError: width

this log is repeated for each program run.

I love the look that has been in your examples! : D

**Comment by desdic** [comment]
Hi :)

Thanks for getting back to me .. can you try to update the source ? I just commited some more fixes last night so maybe this is one of the bugs.

Now when I run the examples I get:

# ./genexamples.sh
#

so all should be fixed now

**Comment by desdic** [comment]
Hi,

Thanks for getting back to me :)

Did you install Pillow and not PIL ? it seems that there is a difference but with a nameclash. Its tested on OSX with Python 2.7.10 and Pillow 2.9.0

/Kim

**Comment by Diphendara** [comment]
Yes, i install pillow, but i just realized pip install default the 2.3 version, now i upgrade and works very well!

Sorry, my fault. Thank you for this wonderful program! : D

I created a lot simpler just to put a grid on my github, but yours is a thousand times better!

**Comment by desdic** [comment]
Thanks :) I used a simple mosaic algorithm in order to get a smoother pegboard

**Comment by Diphendara** [comment]
In order to enable them to persons not used python installed I will try to do what you've done your :)

**Comment by desdic** [comment]
:) feel free to take or use it as you like

**Comment by Diphendara** [comment]
Thank you very much! :D
